### PR TITLE
Ibus telemetry

### PR DESCRIPTION
**Pull request by Argosse**

### CODE REVIEW

**Comment by unitware** [comment]
My plan is to test the current firmware in the coming days and issue a pull request to master. 
I'd prefer to not have test code in the branch until then.

Did I miss something here? This is temporary test code right?

Apart from that, the unit tests does not pass.

**Comment by Argosse** [comment]
Yes temporary test code.

And I find it failed at IbusRespondToSensorTypeQueryWrongAddress , Ive added a new type of sensor to enum ibusSensorType_e and SENSOR_ADDRESS_LOOKUP , my hope was to have cleanflight respond to the receiver when it queries for sensor addresses, I'd like to implement gps latitude and longitude being sent FC(cleanflight) -> receiver -> transmitter sensor display. Looking at the test results I think I may have added to the wrong enum; and cleanflight is responding with an improper sensor type. 

If you could point me in the right direction that would be awesome. I'm hoping to get my i6s and ia6b back soon for hands on testing.

**Comment by Argosse** [comment]
Should I have closed the first pull request before changing files? I'm new to github + travisci. Is there a way to run the tests on my own without having to clutter with a pull request.

Btw:  The latest pull request Commit 8a094ef and current state of my repository has no new test code and only cleans up the switch statement in dispatchMeasurementRequest.

**Comment by unitware** [comment]
I can see that you managed to set up your own TravisCi account, awesome!
It's also possible to build the firmware and run tests locally before pushing as you probably know, it gives much faster turnaround time (make -j test will make it even more faster)

You were probably right in adding a new enum, the trick will be to let the transiever recognize the new sensor type. I do not think there is a position sensor type in the official firmware but I may be wrong. The tests should then be updated to allow for 4 sensors instead of three, the failing test is a good place to start looking in order to fix that.

**Pull request closed without merging**
